name: CI tests with docker container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
      -
        name: Build and export locally
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: test umbrella sampling
        run: |
          docker run -t pysages bash -c "cd PySAGES/examples/umbrella_sampling/ && ./run.sh"
