name: CI tests with docker container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pysages:latest
          outputs: type=docker,dest=/tmp/pysages.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pysages
          path: /tmp/pysages.tar

  harmonic-bias-hoomd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      -
        name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -t pysages bash -c "cd PySAGES/examples/harmonic_bias/ && ./run.sh"

  abf-alanine-dipeptide-openmm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      -
        name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -t pysages bash -c "cd PySAGES/examples/abf/ && python3 ./alanine-dipeptide_openmm.py"
