name: CI tests with docker container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pysages:latest
          outputs: type=docker,dest=/tmp/pysages.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pysages
          path: /tmp/pysages.tar
          retention-days: 1

  forward-flux-sampling:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -v /tmp:/tmp -t pysages bash -c "cd PySAGES/examples/openmm/ && python3 forward_flux_sampling.py --cv-start=80 --cv-distance=2 --window-number=2 --sampling-steps=50 --replicas=5"

  abf-alanine-dipeptide-openmm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -t pysages bash -c "cd PySAGES/examples/openmm/abf/ && python3 ./alanine-dipeptide_openmm.py"
  metad-alanine-dipeptide-openmm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -t pysages bash -c "cd PySAGES/examples/openmm/metad/ && python3 ./alanine-dipeptide.py --time-steps=25"

  metad-hoomd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -v/tmp:/tmp -t pysages bash -c "cd PySAGES/examples/hoomd-blue/metad/ && python3 butane.py --use-grids=1 --time-steps=5000"

  harmonic-bias-hoomd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -v/tmp:/tmp -t pysages bash -c "cd PySAGES/examples/hoomd-blue/harmonic_bias/ && ./run.sh && mv hist.pdf /tmp/"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: harmonic-hist.pdf
          path: /tmp/hist.pdf
          retention-days: 7

  umbrella-integration-hoomd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pysages
          path: /tmp
      - name: Load and run test
        run: |
          docker load --input /tmp/pysages.tar
          docker run -v /tmp:/tmp -t pysages bash -c "cd PySAGES/examples/hoomd-blue/umbrella_integration && python3 ./gen_gsd.py && python3 integration.py --replicas=5 --time-steps=1000 && mkdir /tmp/plots && mv *.pdf /tmp/plots/"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: umbrella-integration-plots
          path: /tmp/plots
          retention-days: 1
