on:
    push:
          branches:
                - main
    pull_request:
          branches:
               - main

defaults:
        run:
                shell: bash
                working-directory: ./

jobs:
        pylint:
                runs-on: ubuntu-20.04
                name: "Testing compliance with pylint coding"
                steps:
                       - uses: actions/checkout@v2
                       - uses: actions/setup-python@v2
                         with:
                             python-version: '3.x'
                       - name: install dependecies
                         run: |
                           pip install pylint flake8
                       - name: test with pylint
                         run: pylint pysages
                       - name: test with flake8
                         run : flake8 pysages
